lazyimageURL = '/lazyimage.jpg'
notfoundimageURL = '/notfound.jpg'
homeImageURL = '/home.png'
illustDbImageURL = '/ilstdbimage'
serverImageURL = '/image'
repoImageURL = '/repoimage'
wsRPCURL = '/wsrpc'
postRPCURL = '/postrpc'
