name: tagged-release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: 安装 Pipenv
        run: pip install pipenv

      - name: Pipenv lock
        run: pipenv lock

      - name: 建立 Python 环境
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: 安装后端依赖
        run: pipenv install

      - name: 建立 node 环境
        uses: actions/setup-node@v3
        with:
           node-version: 14

      - name: 建立 quasar 环境
        run: |
          npm i -g npm
          npm i -g @quasar/cli

      - name: 安装前端依赖
        run: npm install

      - name: 打包前端
        run: npm build

      - name: 构建 wheel
        run: |
          pip install wheel
          python setup.py bdist_wheel

      - name: 下载 Python Embed
        run: curl -o dist/python.zip https://www.python.org/ftp/python/3.10.4/python-3.10.4-embed-amd64.zip

      - name: 解压 Python Embed
        run: unzip dist/python.zip -d dist/package_base

      - name: 安装库
        run: |
          from os import listdir, system
          whl = [f for f in listdir('dist') if f.endswith('.whl')][0]
          system(f'pip install dist/{whl}[accelerate_fuzzywuzzy] --prefix dist/package_base -I')
        shell: python

      - name: 修改 python310._pth
        run: |
          with open('dist/package_base/python310._pth', 'a', encoding='utf-8') as wf:
            wf.write('\n./Lib/site-packages\n')
        shell: python

      - name: 复制入口文件、配置、README并压缩
        run: python dist_stuff/mk_win_pkg.py
      
      - name: 获得最新的 Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: 创建 Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_releases_tag: ${{ steps.get-latest-tag.outputs.tag }}
          files: |
            dist/PixivWahu-win64.zip
            dist/*.whl


